---
title: "Exemplos de uso"
date: |
  | Em atualização
  <!-- | Atualizado em  -->
  | `r format(Sys.Date(), c("%d de %B de %Y"))`
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = NULL
)
```

```{r setup, message=FALSE}
library(csapAIH)
library(dplyr) 
```

<!-- # Apresentação de resultados  -->

<!-- ## Resumo de importação de dados -->

<!-- Um resumo de importação, apresentado durante a realização do trabalho, é guardado como atributo do banco de dados e pode ser recuperado com as funções `attr()` ou `attributes()`: -->

<!-- ```{r} -->
<!-- csap <- fetchcsap('RS', 2018, mesfim = 1, anofim = 2018, periodo = "competencia") -->

<!-- attr(csap, "resumo") -->
<!-- # attributes(csap)$resumo -->
<!-- ``` -->

<!-- Em tabela para apresentação: -->

<!-- ```{r} -->
<!-- attributes(csap)$resumo |> -->
<!--   knitr::kable(format.args = c(big.mark = ".", decimal.mark = ","),  -->
<!--                col.names = c("Ação", "N", "%", "Objeto") ) |> -->
<!--   suppressWarnings() -->
<!-- ``` -->

<!-- ## Tabela "bruta" -->

<!-- A função `descreveCSAP` gera, a partir de um comando muito simples, uma tabela pronta para apresentação, com as frequências brutas e absolutas das CSAP por grupo de causa. -->

<!-- ```{r} -->
<!-- descreveCSAP(csap) -->
<!-- ``` -->

<!-- ## Tabela para apresentação -->

<!-- ```{r} -->
<!-- descreveCSAP(csap) |> -->
<!--   knitr::kable(align = c('l', rep('r', 3))) -->
<!-- ``` -->

<!-- Entretanto, ao transformar os valores para o formato latino, sua classe se transforma em `character` e assim é impossível realizar cálculos com esse output. Além disso, não serve para publicações em inglês. Por isso a função `descreveCSAP` permanecerá no pacote mas seu desenvolvimento seguirá em outra função, agora de nome `tabCSAP`. Nessa nova função, a apresentação de uma tabela formatada se faz a partir do argumento `format = TRUE`. Por padrão esse argumento é `FALSE`, o que permite operações matemáticas com os valores da tabela (um `data.frame`, na verdade), como veremos em seguida. -->

<!-- A função `tabCSAP` permite também a apresentação da tabela em inglês ou espanhol, através do argumento `lang`: -->

<!-- ```{r} -->
<!-- tabCSAP(csap$grupo, digits = 1, lang = "en", format = T) |> -->
<!--   knitr::kable(align = c('l', rep('r', 3))) -->

<!-- tabCSAP(csap$grupo, digits = 1, lang = "es", format = T) |> -->
<!--   knitr::kable(align = c('l', rep('r', 3))) -->
<!-- ``` -->

<!-- Finalmente, [vimos](#lista) que a função `tabCSAP` permite ainda a apresentação da lista em 20 grupos de causa. Assim, se as CSAP foram classificadas em 20 grupos -- usando, por exemplo o argumento `lista = "Alfradique"` em `csapAIH()` --, essa tabela deve ser apresentada com `tabCSAP` e não com `descreveCSAP`. Note ainda que, à diferença de `descreveCSAP`, `tabCSAP` exige o nome da variável com o grupo de causas. -->

<!-- ```{r} -->
<!-- AIHRS2021 <- microdatasus::fetch_datasus(year_start = 2021, 1, 2021, 12, uf = "RS", information_system = "SIH-RD") -->

<!-- listaOPS <- csapAIH(AIHRS2021, lista = "Alfradique") -->
<!-- # descreveCSAP(listaOPS) # Retorna o erro: "O vetor precisa ter os 19 grupos da Lista Brasileira. -->
<!-- #   Se essa for a lista 'Alfradique' use 'tabCSAP'."" -->
<!-- tabCSAP(listaOPS$grupo) -->
<!-- ``` -->


<!-- ## Calcular taxas -->

<!-- **Exemplo: cálculo das taxas brutas de ICSAP por grupo de causa em Cerro Largo, RS, 2021:** -->

<!-- O código IBGE (os seis primeiros dígitos) de Cerro Largo é "430520". -->

<!-- ### As ICSAP -->

<!-- Selecionamos as informações sobre residentes de Cerro Largo em nosso banco de dados da AIH em 2021. -->

<!-- ```{r} -->
<!-- claih <- AIHRS2021 %>%  -->
<!--   filter(MUNIC_RES == "430520") %>%  -->
<!--   droplevels() %>%  -->
<!--   csapAIH() -->
<!-- ``` -->


<!-- ### A população -->

<!-- ```{r} -->
<!-- clpop <- ler_popbr(2021) %>%  -->
<!--   filter(munic_res == "430520") %>%  -->
<!--   group_by(sexo, fxetar5) %>%  -->
<!--   reframe(pop = sum(populacao)) -->

<!-- clpop %>%  -->
<!--   tidyr::pivot_wider(names_from = sexo, values_from = pop) -->
<!-- ``` -->

<!-- ### A tabela com as taxas -->

<!-- ```{r} -->
<!-- tabCSAP(claih$grupo) %>%  -->
<!--   mutate(taxa = casos / sum(clpop$pop)*10000) %>%  -->
<!--   knitr::kable(format.args = list(decimal.mark = ",", big.mark = "."), digits = 1, caption = paste("ICSAP em Cerro Largo, RS, 2021. Taxas por 10.000 hab.")) -->
<!-- ``` -->


<!-- ## Gráficos -->

<!-- ```{r out.width="50%", fig.align='center', message=FALSE} -->
<!-- #| fig.alt: > -->
<!-- #|   Gráfico de barras com a distribuição proporcional  -->
<!-- #|   dos grupos de causa CSAP entre as ICSAP -->

<!-- gr <- desenhaCSAP(csap, titulo = "auto", onde = "RS", quando = 2018, limsup = .18, x.size = 4) -->
<!-- gr -->
<!-- ``` -->

<!-- ### Estratificado por categorias de outra variável presente no banco de dados: -->

<!-- Observe que ao estratificar o gráfico mantém a ordenação por frequência da variável em seu todo, sem a estratificação, quando o argumento `ordenar = TRUE`(padrão). -->

<!-- ```{r out.width="75%", fig.align='center', fig.show='hold', fig.height=4} -->
<!-- #| fig.alt: > -->
<!-- #|   O gráfico anterior por estratos de sexo -->

<!-- rot <- ggplot2::as_labeller(c("masc" = "Masculino", "fem" = "Feminino", "(all)" = "Total")) -->
<!-- gr + ggplot2::facet_grid(~ sexo, margins = TRUE, labeller = rot) -->

<!-- gr + ggplot2::facet_wrap(~ munres == "431490",  -->
<!--                          labeller = ggplot2::as_labeller(c("FALSE" = "Interior",  -->
<!--                                                            "TRUE" = "Capital"))) -->
<!-- ``` -->

<!-- ```{r out.width="80%", fig.cap="Mortalidade por CSAP por grupos de causa, por sexo e faixa etária. RS, 2021."} -->
<!-- #| fig.alt: > -->
<!-- #|   Gráfico da distribuição proporcional por grupo de causa entre as ICSAP, -->
<!-- #|   por estratos de sexo -->

<!-- DORS2021 %>%  -->
<!--   filter(!is.na(SEXO), !is.na(idade)) %>%  -->
<!--   desenhaCSAP(x.size = 7, y.size = 8) +  -->
<!--     ggplot2::facet_grid(SEXO ~ fxetar3) -->
<!-- ``` -->

